### ISSUE TITLE
MongoDB output (isodate and generateId parameters)

### ISSUE THREAD

**Issue by Danny-Blackjack** [elastic/logstash-contrib#61]
Hi,

I am using logstash to write the events into elasticsearch and mongodb. I ran into some issues, but also found a possible fix.

This is the logstash configuration:
```
output {
    mongodb {
      uri => "mongodb://elasticsearch-server:27017"
      database => "msops"
      collection => "logstash_%{type}"
      #isodate => true
    }
    elasticsearch {
      host => "elasticsearch-server"
    }
}
```

All works well by default. 
I ran into problems when setting the MongoDB @timestamp as an isodate using 'isodate => true'. This causes an exception "Failed to flush outgoing items" in logstash (see full stack further below), causing the elasticsearch flush to fail. Interesting how the mongodb output plugin can cause the ES output to fail.

I also run into problems setting documentId => true'. Here the problem was in ES server, with the mongodb '_id' identifier not matching the ES one. (see also 2nd stack trace below).

I think I found the problem in lib/logstash/outputs/mongodb.rb. Line 59 'document=event.to_hash' makes the mongodb document instance point to the same ES event instance. So changing the @timestamp or _id changed the document/event for both mongodb output and ES output. The fix -which works- is to create a new Hash instance in line 59:
```document = Hash.new { event.to_hash }```
(I'm not a Ruby developer though, so there maybe better ways to do this).

```Ruby
      if @isodate
        # the mongodb driver wants time values as a ruby Time object.
        # set the @timestamp value of the document to a ruby Time object, then.
        #document = event.to_hash
       # Possible fix: create a new Hash instance for mongodb
        document = Hash.new { event.to_hash }
      else
        # Note: .merge creates a new Hash
        document = event.to_hash.merge("@timestamp" => event["@timestamp"].to_json)
      end
```

Using logstash 1.4.1 and logstash-contrub on Java 6 runtime.

```
isodate => true exception
{:timestamp=>"2014-06-03T10:39:58.269000+1000", :message=>"Failed to flush outgoing items", :outgoing_count=>2, :exception=>java.lang.ClassCastException: org.jruby.RubySymbol cannot be cast to java.lang.String, :backtrace=>["org.elasticsearch.common.xcontent.XContentBuilder.writeMap(org/elasticsearch/common/xcontent/XContentBuilder.java:1095)", "org.elasticsearch.common.xcontent.XContentBuilder.map(org/elasticsearch/common/xcontent/XContentBuilder.java:1015)", "org.elasticsearch.action.index.IndexRequest.source(org/elasticsearch/action/index/IndexRequest.java:338)", "org.elasticsearch.action.index.IndexRequest.source(org/elasticsearch/action/index/IndexRequest.java:327)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:597)", "LogStash::Outputs::Elasticsearch::Protocols::NodeClient.build_request(/home/didata/projects/workspace_monitoring/installs/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:217)", "LogStash::Outputs::Elasticsearch::Protocols::NodeClient.build_request(/home/didata/projects/workspace_monitoring/installs/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:217)", "LogStash::Outputs::Elasticsearch::Protocols::NodeClient.bulk(/home/didata/projects/workspace_monitoring/installs/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:205)", "LogStash::Outputs::Elasticsearch::Protocols::NodeClient.bulk(/home/didata/projects/workspace_monitoring/installs/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:205)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)", "LogStash::Outputs::Elasticsearch::Protocols::NodeClient.bulk(/home/didata/projects/workspace_monitoring/installs/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:204)", "LogStash::Outputs::Elasticsearch::Protocols::NodeClient.bulk(/home/didata/projects/workspace_monitoring/installs/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:204)", "LogStash::Outputs::ElasticSearch.flush(/home/didata/projects/workspace_monitoring/installs/logstash/lib/logstash/outputs/elasticsearch.rb:321)", "LogStash::Outputs::ElasticSearch.flush(/home/didata/projects/workspace_monitoring/installs/logstash/lib/logstash/outputs/elasticsearch.rb:321)", "RUBY.buffer_flush(/home/didata/projects/workspace_monitoring/installs/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219)", "org.jruby.RubyHash.each(org/jruby/RubyHash.java:1339)", "RUBY.buffer_flush(/home/didata/projects/workspace_monitoring/installs/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216)", "RUBY.buffer_initialize(/home/didata/projects/workspace_monitoring/installs/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:112)", "org.jruby.RubyKernel.loop(org/jruby/RubyKernel.java:1521)", "RUBY.buffer_initialize(/home/didata/projects/workspace_monitoring/installs/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:110)", "java.lang.Thread.run(java/lang/Thread.java:662)"], :level=>:warn}
```

``` 
documentId => true
2014-06-02 08:45:04,949][DEBUG][action.bulk              ] [Hawkshaw] [logstash-2014.06.01][1] failed to execute bulk item (index) index {[logstash-2014.06.01][collectd][GjZqRd6UTpeVQNv9BkksUg], source[{"@version":"1","@timestamp":"2014-06-01T22:44:28.437Z","host":"mint15","plugin":"load","collectd_type":"load","shortterm":3.34,"midterm":2.56,"longterm":1.72,"type":"collectd","_id":"538baccce4b032f7fb3523e9"}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [_id]
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:418)
	at org.elasticsearch.index.mapper.internal.IdFieldMapper.parse(IdFieldMapper.java:291)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:616)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:469)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:515)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:462)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:363)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:427)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:160)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:556)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:426)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Provided id [GjZqRd6UTpeVQNv9BkksUg] does not match the content one [538baccce4b032f7fb3523e9]
	at org.elasticsearch.index.mapper.internal.IdFieldMapper.parseCreateField(IdFieldMapper.java:310)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:408)
	... 13 more
```

**Comment by rakesh91** [comment]
@Danny-Blackjack Thanks a lot. You just saved my day.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-mongodb/issues/6. Let's continue the discussion there! :)
